# Available options: https://codeberg.org/dnkl/foot/src/branch/master/foot.ini
# Manual: https://man.archlinux.org/man/foot.ini.5.en

[main]
	font=FiraCode Nerd Font:size=10

[cursor]
	style=beam
	beam-thickness=1
	blink=yes
	blink-rate=600
